# Generated by Django 4.1 on 2022-09-01 23:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_n', models.DateField(blank=True, null=True)),
                ('fecha_d', models.DateField(blank=True, null=True, verbose_name='Fallecido')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_g', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, help_text='ID único de este ejemplar', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=50)),
                ('sumario', models.TextField(max_length=120)),
                ('idioma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_libro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único de este ejemplar', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('fecha_devol', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('a', 'Agotado'), ('p', 'Prestado'), ('d', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Disponibilidad del libro', max_length=1)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibCatalogo.libros')),
            ],
        ),
    ]
