# Generated by Django 4.1 on 2022-09-03 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_libro',
        ),
    ]
