# Generated by Django 4.1 on 2022-09-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0002_delete_estado_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='fecha_n',
            field=models.DateField(blank=True, null=True),
        ),
    ]
