# Generated by Django 4.1 on 2022-09-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0003_usuarios_fecha_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='sumario',
            field=models.TextField(max_length=250),
        ),
    ]
