# Generated by Django 4.1 on 2022-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibCatalogo', '0004_alter_libros_sumario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autores',
            name='fecha_d',
            field=models.DateField(blank=True, null=True),
        ),
    ]
